# Generated by Django 3.1.2 on 2020-10-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('raw_type', models.CharField(choices=[('Seeds', 'Seeds'), ('Pesticides', 'Pesticides'), ('Fertilizers', 'Fertilizers')], default='Seeds', max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('crop_type', models.CharField(choices=[('Edible', 'Edible'), ('Commercial', 'Commercial')], default='Edible', max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmer')),
            ],
        ),
    ]
