# Generated by Django 2.2.9 on 2020-11-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_farmerorders_sellerorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerorders',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Consumer'),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Farmer'),
        ),
    ]
